openapi: 3.0.3

info:
  title: Order Management API
  version: 1.0.0
  description: |
    API generada a partir de la colección Postman entregada. 
    Incluye módulos Admin y Client, autenticación vía Bearer Token 
    y manejo multi-tenant mediante encabezado X-Tenant-ID.

servers:
  - url: http://localhost:8000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  #########################
  # SCHEMAS
  #########################

  schemas:

    #########################
    # Shared Error Format
    #########################

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Validation error"
        errors:
          type: object
          example: { "email": ["The email field is required"] }

    #########################
    # ADMIN - CLIENTS
    #########################

    Client:
      type: object
      properties:
        id:
          type: integer
          example: 12
        name:
          type: string
          example: "Demo Client"
        email:
          type: string
          example: "demo@client.com"
        status:
          type: string
          example: "active"
        created_at:
          type: string
          example: "2025-11-08T20:00:00.000Z"
        updated_at:
          type: string
          example: "2025-11-08T20:00:00.000Z"

    ClientCreateInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        status:
          type: string
        password:
          type: string
      example:
        name: "Demo Client"
        email: "demo@client.com"
        status: "active"
        password: "secret987"

    ClientUpdateInput:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
      example:
        name: "Updated Name"
        status: "active"

    #########################
    # AUTH
    #########################

    LoginInput:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          example: "user@example.com"
        password:
          type: string
          example: "secret123"

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: "1|Xyz123abc.token.value"

    #########################
    # ORDERS
    #########################

    OrderItemInput:
      type: object
      required: [name, quantity, price]
      properties:
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float

    OrderCreateInput:
      type: object
      required: [items]
      properties:
        customer_name:
          type: string
        customer_email:
          type: string
        customer_phone:
          type: string
        customer_address:
          type: string
        customer_city:
          type: string
        customer_country:
          type: string
        customer_tax_id:
          type: string
        notes:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemInput"

    OrderItem:
      type: object
      properties:
        id:
          type: integer
        order_id:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
        subtotal:
          type: number

    Order:
      type: object
      properties:
        id:
          type: integer
        client_id:
          type: integer
        user_id:
          type: integer
        status:
          type: string
          example: "created"
        total:
          type: number
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"

security:
  - bearerAuth: []

paths:

  #################################################
  # ✅ ADMIN - CLIENTS
  #################################################

  /admin/clients:
    post:
      summary: Create a client
      tags: [Admin Clients]
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: X-API-Version
          schema: { type: string }
          example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientCreateInput"
      responses:
        '201':
          description: Client created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    $ref: "#/components/schemas/Client"
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      summary: Get all clients
      tags: [Admin Clients]
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: X-API-Version
          schema: { type: string }
      responses:
        '200':
          description: List of clients
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Client"

  /admin/clients/{id}:
    get:
      summary: Get client by ID
      tags: [Admin Clients]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
        - in: header
          name: X-API-Version
          schema: { type: string }
      responses:
        '200':
          description: Client found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    $ref: "#/components/schemas/Client"
        '404':
          description: Not found

    put:
      summary: Update a client
      tags: [Admin Clients]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientUpdateInput"
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    $ref: "#/components/schemas/Client"
        '404':
          description: Not found

    delete:
      summary: Delete a client
      tags: [Admin Clients]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Deleted
        '404':
          description: Not found

  #################################################
  # ✅ ADMIN - AUTH
  #################################################

  /admin/login:
    post:
      summary: Admin login
      tags: [Admin Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: Unauthorized

  /admin/me:
    get:
      summary: Get authenticated admin
      tags: [Admin Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Admin info

  #################################################
  # ✅ CLIENT - LOGIN
  #################################################

  /login:
    post:
      summary: Client login
      tags: [Client Auth]
      parameters:
        - name: X-Tenant-ID
          in: header
          required: true
          schema: { type: integer }
          example: 12
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

  #################################################
  # ✅ CLIENT - ORDERS
  #################################################

  /orders:
    post:
      summary: Create a new order
      tags: [Client Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: X-Tenant-ID
          in: header
          required: true
          schema: { type: integer }
          example: 12
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateInput"
      responses:
        '201':
          description: Order created
        '422':
          description: Validation error

  /orders/{id}:
    get:
      summary: Get order by ID
      tags: [Client Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
        - name: X-Tenant-ID
          in: header
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        '404':
          description: Not found

  /clients/{id}/orders:
    get:
      summary: Get all orders for a client
      tags: [Client Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
        - name: X-Tenant-ID
          in: header
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Orders list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        '403':
          description: Forbidden (wrong tenant)
